In [5]:
import pandas as pd

freedom_data = 'starting_data/freedom.csv'
happiness_data = 'starting_data/happiness.csv'
kaggle_data = 'starting_data/kaggle.csv'

freedom_df = pd.read_csv(freedom_data)
happiness_df = pd.read_csv(happiness_data)

kaggle_df = pd.read_csv(kaggle_data)
kaggle_df = kaggle_df.loc[kaggle_df['year'] == 2016]
kaggle_df = kaggle_df[["countries","hf_score"]]
kaggle_df.columns = ["Country", "Human Freedom"]

freedom_df.columns=["Country", "Personal Freedom", "Economic Freedom"]

freedom_and_happiness = pd.merge(freedom_df,happiness_df, on="Country")
freedom_and_happiness = pd.merge(freedom_and_happiness,kaggle_df, on="Country")

freedom_and_happiness["Happiness score"] = round(freedom_and_happiness["Happiness score"],2)
freedom_and_happiness["Human Freedom"] = round(freedom_and_happiness["Human Freedom"],2)

freedom_and_happiness = freedom_and_happiness.set_index('Country')
freedom_and_happiness.head()

,Personal Freedom,Economic Freedom,Happiness score,Human Freedom
Country,,,,
Netherlands,9.40,7.71,7.49,8.55
Norway,9.34,7.60,7.55,8.47
Sweden,9.33,7.44,7.34,8.39
Denmark,9.33,7.77,7.60,8.55
Finland,9.29,7.65,7.77,8.47